export default {
    SAVE_USER: "SAVE_USER",
    ADD_COUNTRY_TO_FAVORITES: "ADD_COUNTRY_TO_FAVORITES_ACTION",


    //ASYNC ACTIONS
    GET_COUNTRIES: "GET_COUNTRIES_ACTION",
    GET_COUNTRIES_PENDING: "GET_COUNTRIES_PENDING",
    GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS"

}